<?php
namespace app\common\controller;
/**
 * 分销商父类
 * User: lirong
 * Date: 2017/6/25
 * Time: 13:03
 */

abstract class Shop extends Common{


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 用于首页数据展示
     * @return mixed
     */
    public abstract function index();

    /**
     * 增加数据
     * @return mixed
     */
    public abstract function create();

    /**
     *修改数据
     * @return mixed
     */
    public abstract function edit();

    /**
     * 移除数据
     * @return mixed
     */
    public abstract function remove();




}